### ISSUE TITLE
Busts Configuration Cache

### ISSUE THREAD

**Issue by chrisjenx** [gradle/common-custom-user-data-gradle-plugin#10]
Trying to enable configuration cache, but it tracks every env value which change regularly

Can we disable/enable different system properties that we actually care about vs trying to capture everything?

**Comment by chrisjenx** [comment]
`java.awt.headless` appears to be the main culprit btw

**Comment by chrisjenx** [comment]
Whats odd I can't see where thats even looked up in the plugin :confused:

**Comment by chrisjenx** [comment]
![image](https://user-images.githubusercontent.com/1167793/151085616-939bd007-2756-40c4-b6f8-9380dbf35b63.png)
![image](https://user-images.githubusercontent.com/1167793/151085645-9894939b-c452-48d7-9d7d-30068238ddc5.png)

**Comment by chrisjenx** [comment]
Oh, looks like a regression in 7.4-rc1, https://github.com/gradle/gradle/issues/19710, feel free to close if you think it's unrelated to this plugin

**Comment by mlopatkin** [comment]
> Oh, looks like a regression in 7.4-rc1, [gradle/gradle#19710](https://github.com/gradle/gradle/issues/19710), feel free to close if you think it's unrelated to this plugin

It looks like the plugin [iterates through all system properties to find out if some start with the given prefix](https://github.com/gradle/common-custom-user-data-gradle-plugin/blob/2fa8835135545654ca32fb15cd6989e5cb8a9d3e/src/main/java/com/gradle/Utils.java#L87-L101). More rigorous tracking of the build configuration inputs added in Gradle 7.4 marks all system properties as inputs in such a case. [A more fine-grained approach](https://github.com/gradle/gradle/issues/13819) is planned but is not yet implemented.

**Comment by chrisjenx** [comment]
Yeah, it's still a regression in 7.4-rc1 as that value is just null and Gradle is treating it as changing each time instead of no change for a null/unset value.
In the interim is there a way to disable the interation through the system props? We really only care about git/ci properties

**Comment by chrisjenx** [comment]
yeah the fix suggested (until they improve again in 7.5) is to change back to `System.properties()`, I'll throw a PR up later to make that change.

**Comment by chrisjenx** [comment]
Opened PR to bring inline with 7.4

**Comment by chrisjenx** [comment]
7.4 was released today

**Comment by etiennestuder** [comment]
FYI, I've also removed the special logic for old versions of IntelliJ IDEA:
https://github.com/gradle/common-custom-user-data-gradle-plugin/commit/7d9f4372e9ee99fc85de9aa7bb414afdd1dc00aa

**Comment by chrisjenx** [comment]
Oh nice. That's what was causing issues but the looks of it anyways

**Comment by chrisjenx** [comment]
Hey, is there an ETA on release?
