### ISSUE TITLE
Fix Build Scan links when running on GitHub Enterprise Server

### ISSUE THREAD

**Issue by erichaagdev** [gradle/common-custom-user-data-gradle-plugin#109]
It is possible to use the GitHub actions with GitHub Enterprise Server. This means that any reference to `github.com` in Build Scan links will be incorrect. For example: 

https://github.com/gradle/common-custom-user-data-gradle-plugin/blob/3908b28b83348c4485bf5d760690b852f4256dba/src/main/java/com/gradle/CustomBuildScanEnhancements.java#L187

Instead of hardcoding `github.com` we should key off of the `GITHUB_SERVER_URL` environment variable. According to the documentation, this environment variable is available on [Enterprise Server](https://docs.github.com/en/enterprise-server@3.7/actions/learn-github-actions/environment-variables#default-environment-variables), [Enterprise Cloud](https://docs.github.com/en/enterprise-cloud@latest/actions/learn-github-actions/environment-variables#default-environment-variables), and [Free](https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables).

This aligns with the GitHub documentation as well:

> If you need to use a workflow run's URL from within a job, you can combine these environment variables: `$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID`

**Comment by etiennestuder** [comment]
@tylerbertrand do you want to take on this issue and have Jerome review it? //cc @clayburn

**Comment by tylerbertrand** [comment]
Sure 👍
