### ISSUE TITLE
Builds from GitHub Actions Windows runners incorrectly tagged as `LOCAL`

### ISSUE THREAD

**Issue by erichaagdev** [gradle/common-custom-user-data-gradle-plugin#115]
See:

- https://github.com/gradle/gradle-enterprise-build-validation-scripts/actions/runs/3766542916/jobs/6403164517#step:6:102
- https://ge.solutions-team.gradle.com/s/npqyejncfgvvi

**Comment by runningcode** [comment]
Do you know what the change is that needs to be made here?
I'm guessing this means that the `GITHUB_ACTIONS` environment variable is likely not able to be picked up in the same way on windows? https://github.com/gradle/common-custom-user-data-gradle-plugin/blob/2a332b4ea80167c0ee26d54b231ec94adfa92832/src/main/java/com/gradle/CustomBuildScanEnhancements.java#L294

**Comment by erichaagdev** [comment]
I don't know for sure, but that is my best guess as well.

**Comment by ribafish** [comment]
This is not an issue of CCUD, it's an issue of WSL, which by default doesn't "forward" env vars set in Windows (host) by default. The only way to forward them is to set them using `WSLENV` - see [discussion](https://github.com/Vampire/setup-wsl/discussions/9) and [Microsoft blog](https://devblogs.microsoft.com/commandline/share-environment-vars-between-wsl-and-windows/). You can also observe that in this [test project](https://github.com/ribafish/kotlinTests/actions/runs/10146123467), where the env vars are printed out. All of them are available with the [default windows shell (pwsh)](https://github.com/ribafish/kotlinTests/actions/runs/10146123467/job/28053822402#step:7:55), but almost none are there with [wsl](https://github.com/ribafish/kotlinTests/actions/runs/10146123467/job/28053822792#step:7:52). When [WSLENV is configured](https://github.com/ribafish/kotlinTests/actions/runs/10159960175/workflow#L28), the [specified vars are available](https://github.com/ribafish/kotlinTests/actions/runs/10159960175/job/28095278023#step:7:59), which also means that [CCUD will tag the build](https://ge.solutions-team.gradle.com/s/t7646azizh7qq#info) correctly, as well as add all of the [other values](https://ge.solutions-team.gradle.com/s/t7646azizh7qq/custom-values#L0-L1).

As such, I've opened a PR to address this for BVS tests on github actions [here](https://github.com/gradle/gradle-enterprise-build-validation-scripts/pull/643).
