### ISSUE TITLE
Git branch tag is broken for CI jenkins builds

### ISSUE THREAD

**Issue by sfc-gh-akazantsev** [gradle/common-custom-user-data-gradle-plugin#13]
There is a bug here https://github.com/gradle/common-custom-user-data-gradle-plugin/blob/7ede73a14680941f66fc4289c334f855c2784730/src/main/java/com/gradle/CustomBuildScanEnhancements.java#L331
as BRANCH_NAME is NOT git branch but jenkins job branch. 
this is same as maven issue https://github.com/gradle/common-custom-user-data-maven-extension/issues/14

**Comment by runningcode** [comment]
As discussed in the other PR this is actually the correct value that we want for the builds this was a misunderstanding.
