### ISSUE TITLE
Add tag for builds which runs with debugger

### ISSUE THREAD

**Issue by audkar** [gradle/common-custom-user-data-gradle-plugin#155]
#### Problem: 
When developers run Gradle tasks with debugger, then build time is misrepresented (as it shows how long developers spend debugging).

#### Example: 
User runs tests with debugger ON and spends 5 minutes.
```
gradle :app:tDUT --debug-jvm
```
Gradle Enterprise logs 5min build time for test task. This sometimes skews our build time averages when someone does heavy debugging for a day.

I would say it would be a useful GE `tag` for everyone. But if it doesn't make sense for you, could you give some hint how I could detect this `--debug-jvm` and register it in our config without breaking config cache?
```kotlin
gradleEnterprise {
    buildScan {
        tag(<??>)
    }
}
```

**Comment by runningcode** [comment]
Hi @audkar ,
You can call `Test#getDebug()` in order to conditionally set a build scan tag for this case.

```
tasks.withType(Test).configureEach {
  if (getDebug()) {
    buildScan.tag("debug")
  }
}
```
This is not something we will add to the CCUD plugin.

**Comment by runningcode** [comment]
Here is an example which is configuration cache compatible, written with KTS build scripts and was tested with Gradle 8.0.2:
```
val scan = buildScan
allprojects {
  tasks.withType<Test>().configureEach {
    doFirst {
      if(debug) {
        scan.tag("debug")
      }
    }
  }
}
```

Please let me know if that works for you.
