### ISSUE TITLE
Migrate build logic to Kotlin DSL

### ISSUE THREAD

**Issue by alllex** [gradle/common-custom-user-data-gradle-plugin#186]
As Gradle went Kotlin DSL first this year, which should migrate all our plugins to Kotlin DSL and use it in the samples too.

This plugin seems to be relatively easily convertible.

**Comment by erichaagdev** [comment]
> which should migrate all our plugins to Kotlin DSL

Are you suggesting we migrate the plugin source from Java to Kotlin?

**Comment by alllex** [comment]
@erichaagdev, I am suggesting to migrate the build logic (build scripts) of this project from Groovy DSL to Kotlin DSL
