### ISSUE TITLE
Calling buildFinished when build is finished is too late

### ISSUE THREAD

**Issue by etiennestuder** [gradle/common-custom-user-data-gradle-plugin#4]
When asynchronously invoking code via buildScan.background, it can happen that this background task finishes _after_ the build has finished. The GE plugin will correctly wait for the background task to finish. The problem in the CCUD plugin is that, currently, the background task invoked from `captureGitMetadata` will add a custom link via buildFinished call - which is too late when the end of the build has already been reached since the GE plugin will no longer allow to add more buildFinished listeners once the build has finished. This can be observed when a warning is printed by the GE plugin at the ened of the build. As explained, this does not happen everytime but under certain conditions.

It seems to me that we should go with the approach we had before: having a list and adding the actions there (in a thread-safe way) and executing them by a single buildFinished listener. Of course we need to be cautious and avoid an infinite loop where an action adds another action.

**Comment by bigdaz** [comment]
We will also have to block in the `buildFinished` handler to wait until the background `git` process has completed. I originally avoided this in an attempt to reduce implementation complexity.

**Comment by etiennestuder** [comment]
> We will also have to block in the buildFinished handler to wait until the background git process has completed. I originally avoided this in an attempt to reduce implementation complexity.

I suggest to separate these two items and as part of this card just fix what causes the current warning.

**Comment by facewindu** [comment]
FYI a customer is affected by that: https://gradle.zendesk.com/agent/tickets/3729

**Comment by etiennestuder** [comment]
@runningcode I also want to take a look at this PR.

**Comment by bigdaz** [comment]
The fix for this issue is available in [v1.6.3 of the common-custom-user-data-gradle-plugin](https://github.com/gradle/common-custom-user-data-gradle-plugin/releases/tag/v1.6.3).

**Comment by etiennestuder** [comment]
@bigdaz I meant the Zendesk ticket

**Comment by etiennestuder** [comment]
//cc @runningcode
