### ISSUE TITLE
Build fails when applying custom user data gradle plugin and gradle enterprise init script

### ISSUE THREAD

**Issue by kyhule** [gradle/common-custom-user-data-gradle-plugin#5]
I recently created an `init.gradle.kts` in my user home `.gradle` directory that applies the gradle enterprise plugin to all projects built on my machine but when I have `com.gradle.common-custom-user-data-gradle-plugin`applied in a project, the build fails with the following error:
```
An exception occurred applying plugin request [id: 'com.gradle.common-custom-user-data-gradle-plugin', version: '1.4.2']
> Failed to apply plugin 'com.gradle.common-custom-user-data-gradle-plugin'.
   > Extension of type 'GradleEnterpriseExtension' does not exist. Currently registered extension types: [ExtraPropertiesExtension, GradleEnterpriseExtension]
```

I am using Gradle 7.3 and the init script I used is basically copy and pasted from [here](https://docs.gradle.com/enterprise/gradle-plugin/#gradle_enterprise) (though I made sure to change the version to 3.6.3) and my `settings.gradle.kts` is:
```
plugins {
    id("com.gradle.enterprise") version "3.6.3"
    id("com.gradle.common-custom-user-data-gradle-plugin") version "1.4.2"
}
```

**Comment by runningcode** [comment]
Hi @kyhule please check the latest versions of the init scripts available here: https://docs.gradle.com/enterprise/gradle-plugin/#gradle_6_x_and_later_3
When using Gradle 6 and the new script you should now be able to apply the Common Custom User Data Gradle plugin. Please let us know if it works. If it doesn't please re-open this issue.
