### ISSUE TITLE
Git Branch Tag is meaningless in GitLab CI

### ISSUE THREAD

**Issue by JavierTobar** [gradle/common-custom-user-data-gradle-plugin#55]
GitLab runners run git in a detached head so whenever the plugin attempts to retrieve the branch in CI it will always return 'head'. This makes developers unable to filter through branches from CI build scans.

I forked the plugin and added the fix.

I was wondering if you guys wanted me to make a PR for this feature, let me know, thanks!

**Comment by runningcode** [comment]
@JavierTobar could you please point us to the fork and the system property you used? I think we might accept this.

**Comment by runningcode** [comment]
I wasn't able to find the branch in your fork. Please point us to it, we are interested.

**Comment by runningcode** [comment]
This was fixed and released in 1.8 https://github.com/gradle/common-custom-user-data-gradle-plugin/tree/v1.8
