### ISSUE TITLE
Document in the README how to apply this plugin

### ISSUE THREAD

**Issue by pgreze** [gradle/common-custom-user-data-gradle-plugin#61]
I had to browse the build.gradle file to discover the plugin ID, which I later applied in my settings.gradle.kts this way:

```kotlin
plugins {
    id("com.gradle.common-custom-user-data-gradle-plugin") version "1.7.2"
}
```

Better document it in the README like similar projects.

**Comment by etiennestuder** [comment]
Thanks for the feedback.

This is documented here, via a link to a full example:
https://github.com/gradle/common-custom-user-data-gradle-plugin#applying-the-published-plugin

It is also document on the link we provide to the plugin portal:
https://plugins.gradle.org/plugin/com.gradle.common-custom-user-data-gradle-plugin
