### ISSUE TITLE
Add system property for enabling/disabling Test Distribution

### ISSUE THREAD

**Issue by melissachang** [gradle/common-custom-user-data-gradle-plugin#62]
If `build.gradle` turned on TD, I'd like to be able to disable TD with this system property.

If `build.gradle` turned off TD, I'd like to be able to enable TD with this system property.

**Comment by runningcode** [comment]
@melissachang This plugin is not related to Test Distribution in any way. Could you please file a support ticket with more information so we can help you with Test Distribution. 

Here is the user manual on test distribution: https://docs.gradle.com/enterprise/test-distribution-gradle-plugin/

**Comment by melissachang** [comment]
Test Distribution is feature of Gradle Enterprise. This repo contains various knobs to configure Gradle Enterprise. It's natural that enabling/disabling Test Distribution is one of the knobs.

Confirmed with @ghale , there is no easy way (system property, env variable) to enable/disable Test Distribution. This repo is a natural place to put it.
