### ISSUE TITLE
IDE sync from IntelliJ IDEA incorrectly tagged as Android Studio

### ISSUE THREAD

**Issue by erichaagdev** [gradle/common-custom-user-data-gradle-plugin#90]
Build Scans are incorrectly tagged as coming from `Android Studio` when running an IDE sync from IntelliJ IDEA. 

See the following build scan run from IntelliJ IDEA as an example: https://scans.gradle.com/s/eh22ik7skmtge

I verified running a task from IntelliJ IDEA is tagged correctly: https://scans.gradle.com/s/5clegna2kwvfi

Additional information:
- Using `com.gradle.common-custom-user-data-gradle-plugin` version 1.8.1
- Using `com.gradle.enterprise` version 3.11.1
- Using IntelliJ IDEA 2022.2.2 (Ultimate Edition)

**Comment by runningcode** [comment]
https://github.com/gradle/common-custom-user-data-gradle-plugin/pull/91
