### ISSUE TITLE
Capture data for builds running on BuildKite

### ISSUE THREAD

**Issue by erichaagdev** [gradle/common-custom-user-data-gradle-plugin#97]
https://buildkite.com/

**Comment by etiennestuder** [comment]
I would like to close this until we see high demand for this CI server amongest the users of the CCUD extension.

**Comment by ZacSweers** [comment]
What constitutes "high demand"? We (Slack) and a number of piers at other companies use buildkite, if any of those help. Would be happy to send a PR if you're open to it

**Comment by runningcode** [comment]
Thanks for the feedback and we are open to a PR here.
